[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "finite-element"  
version = "1.01"
dependencies = [
  "numpy",
  "matplotlib",
  "pytest",
  "scipy",
  "pickle",
  "mpl_toolkits"
  ]
  